### ISSUE TITLE
Observability docs reorganization

### ISSUE THREAD

**Issue by tcnghia** [dapr/docs#1182]
**What content needs to be created or modified?**
The observability doc pages have been growing organically for a while, and needs some pruning/reorganization to prepare for Dapr v1.0.

**Describe the solution you'd like**

- [x] Revamp observability concept page (https://github.com/dapr/docs/issues/1184): to make distinction between observing your app with Dapr's help and observing Dapr sidecars and service plane, as well as clarifying the OpenTelemetry section. Use scenario perspective rather than technology overview.
- [x] Developing applications > Building blocks > Observability needs to only contains developer-centric documentation (https://github.com/dapr/docs/issues/1185).
- [x] Operations > Monitoring pages needs to restructure (https://github.com/dapr/docs/issues/1186). Should look like this:
  - Operations
      - Monitoring
          - Tracing
              - Configure your application for tracing (currently under Troubleshooting)
              - Collect traces with OpenTelemetry collector (currently App Insights specific) – also add a self-hosted mode guidance
              - Tools
                  - Zipkin
                  - Jaeger
                  - Application Insights
                  - New Relic
      - Metrics
          - Grafna
          - Prometheus
      - Logs
          - Fluentd

**Comment by tcnghia** [comment]
@msfussell can you please help going through the docs one more time to see if there are additional improvements we can add before releasing v1.0?  Thanks
