### ISSUE TITLE
SDK documentation gaps

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#2770]
We need to fill documentation gaps in SDK docs, especially with focus on SDK improvements for 1.9 release. SDK doc areas are missing docs for the following building blocks: 

[**Go**](https://github.com/dapr/go-sdk)
- [x] Query State dapr/go-sdk#431
- [x] Actors dapr/go-sdk#431
- [x] Config Get
- [x] Config Subscribe
- [x] Distributed Lock

[**Python**](https://github.com/dapr/python-sdk)
- [x] Distributed Lock dapr/python-sdk#567
- #3451

[**Java** ](https://github.com/dapr/java-sdk)
- [x] Input Bindings dapr/java-sdk#776
- [x] Distributed Lock dapr/java-sdk#930)

[**.NET**](https://github.com/dapr/dotnet-sdk)
- [x] Distributed Lock dapr/dotnet-sdk#1095

[**JS**](https://github.com/dapr/js-sdk)
- [x] Config Subscribe dapr/js-sdk#524
- [x] Distributed Lock dapr/js-sdk#362
