### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [dapr/docs#2861]
This issue is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to a suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks

- [x] From the website data stream (`G-60C6Q1ETC1`),
    configure cross-domain measurement for domains _ending with_ **docs.dapr.io**
- [x] Connect `UA-58468480-3` from GA4 stream
- [ ] Configure GA4 website ID ([gtag.js]) for each release:
  - [x] v1.10 - #2945
  - [x] v1.9 - #2941
  - [x] v1.8 - #2950
  - [x] v1.7 - #2962
  - [x] v1.6 - #2963
  - [ ] ... (list to be completed) ...
- [x] Confirm that the GA4 site tag is receiving events -- [tagassistant.google.com](https://tagassistant.google.com/) was used to confirm
- [x] Confirm that the UA site tag, `UA-58468480-3`, is still receiving events

Notes:

- For the main repo issue, see https://github.com/dapr/website/issues/71
- Each doc version is under it's own branch, and each is separately configured to use the UA ID
- Related: #2943

/cc @caniszczyk @nate-double-u

---

Current website analytics info: `UA-149338238-3` registered via old `analytics.js` library.

[connect]: https://support.google.com/analytics/answer/9973999
[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs
[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
I understand that this is the repo for docs only. Still I'll be using this as a tracking issue for the migration to GA4 of the blog and main site too.

**Comment by chalin** [comment]
Each doc version is under its own branch, and has its own individually configured UA ID. It'll be tedious to update all of those.

Do maintainers know if Azure Static Web Apps supports something like [Netlify snippet injection]? That would make the update to GA4 much easier for now, and in the future if the ID needs to be updated.

[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
Done:

> ✅ Connect `UA-58468480-3` from GA4 stream

Per @msfussell's 👍 given in https://github.com/dapr/docs/pull/2941#issuecomment-1306673952.

Also done:

> ✅ From the website data stream (`G-60C6Q1ETC1`),
    configure cross-domain measurement for domains _ending with_ **docs.dapr.io**

**Comment by chalin** [comment]
Docs Analytics for the past 6 months (2022/05/08 - 2022/11/08):

![Dapr-docs analytics past May to Nov 2022](https://user-images.githubusercontent.com/4140793/200950570-023d8816-c668-4b83-b365-5c4754888831.jpg)

@msfussell @greenie-msft:

- What's the suggested cutoff point in terms of doc versions, beyond which we don't update the GA ID? Or do you want to do all in the list above?
- The rank of `v0.11` in that list surprised me, given that it's pre v1.

**Comment by chalin** [comment]
I've created a doc-pages-only custom report. For a screenshot, see: https://github.com/dapr/website/issues/71#issuecomment-1310629107.

**Comment by msfussell** [comment]
> I've created a doc-pages-only custom report. For a screenshot, see: [dapr/website#71 (comment)](https://github.com/dapr/website/issues/71#issuecomment-1310629107).

We do not need to go back more than three releases. 1.7, 1.8 and 1.9 are enough. Then 1.10 is the upcoming release in Feb 2023. Those 4 releases.

**Comment by msfussell** [comment]
Resolved
