### ISSUE TITLE
Actors building block docs refresh

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#3257]
Refresh/update/edit docs under [Developing Applications/Building Blocks/Actors](https://docs.dapr.io/developing-applications/building-blocks/actors/)

Related issues:
- #3240 
- #3042 
- #2766 
- #1298 

Still need:
- [x] Make how-to more of a how-to
- [x] Add updated diagrams
- [x] Add actor types and ids per SDK: #3440 
- [x] Add configuration format for JS SDK in addition to the Go SDK #3439 
- [x] Create quickstart docs and add to overview #3309 
- [x] Add a diagram [to the actor overview workflows vs actors section] that shows the layering for statement management, actors and workflow. @msfussell

**Comment by hhunter-ms** [comment]
also need diagram for: 
I would consider adding a diagram [to the actor overview workflows vs actors section] that shows the layering for statement management, actors and workflow. I an draw this for you and we can add this after the refactoring.
